name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      # ç›¸å½“äº git clone åˆ°æœåŠ¡å™¨
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      # åœ¨æœåŠ¡å™¨ä¸Šå®‰è£… Node.js ç¯å¢ƒ
      - name: Setup Node.js environment ğŸ“¦
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1

      # å®‰è£…ä¾èµ–
      - name: Install Dependencies ğŸ”¨
        run: npm install

      # æ„å»ºé™æ€é¡µé¢å¹¶éƒ¨ç½²
      - name: Build and Deploy ğŸš€
        env:
          token: ${{ secrets.HEXO_DEPLOY }}
        run: |
          git config --global user.email "explorer-dong@foxmail.com"
          git config --global user.name "Mr_Dwj"
          npm run build
          npm run deploy
